color0 #151312
color1 #ffb4ab
color2 #e3beba
color3 #d6c2c0
color4 #d2c6a6
color5 #e3beba
color6 #d6c2c0
color7 #e8e1e0
color8 #9c8d8c
color9 #ffb4ab
color10 #e3beba
color11 #d6c2c0
color12 #d2c6a6
color13 #e3beba
color14 #d6c2c0
color15 #e8e1e0

cursor                #e8e1e0
cursor_text_color     #151312
background            #151312
foreground            #e8e1e0
selection_foreground  #d3c3c1
selection_background  #504443
active_border_color   #e3beba
inactive_border_color #504443
url_color             #e3beba

active_tab_foreground   #422a28
active_tab_background   #e3beba
inactive_tab_foreground #d3c3c1
inactive_tab_background #504443
cursor_trail_color      #d3c3c1
