# https://wiki.hypr.land/Configuring/Window-Rules/ for more
# https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# WindowRule Bluetooth
windowrule {
  name = windowrule-1
  float = on
  size = 700 500
  match:class = ^(kitty)$
  match:title = ^(bluetui)$
}

windowrule {
  name = windowrule-2
  move = (relcursor) (0) (0)
  match:class = ^^(kitty)$
  match:title = ^(bluetui)$
}


# WindowRule Audio
windowrule {
  name = windowrule-3
  float = on
  size = 800 500
  move = (relcursor) (0) (0)
  match:class = ^(pavucontrol|org\.pulseaudio\.pavucontrol)$
}


# WindowRule Network
windowrule {
  name = windowrule-4
  float = on
  size = 700 500
  match:class = ^(kitty)$
  match:title = ^(nmtui)$
}

windowrule {
  name = windowrule-5
  move = (relcursor) (0) (0)
  match:class = ^^(kitty)$
  match:title = ^(nmtui)$
}


# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-6
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-7
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}
