"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](#ffb3b2)\
$username\
$os\
$hostname\
[](fg:#ffb3b2 bg:#733334)\
$directory\
[](fg:#733334 bg:#5d3f3f)\
$git_branch\
$git_status\
[](fg:#5d3f3f bg:#322827)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#322827 bg:#271d1d)\
$time\
[ ](fg:#271d1d)\
"""

[username]
show_always = true
style_user = "bg:#ffb3b2 fg:#561d1f"
style_root = "bg:#ffb3b2 fg:#561d1f"
format = '[ $user ](bold $style)'
disabled = false

[hostname]
ssh_only = false
style = "bg:#ffb3b2 fg:#561d1f"
format = '[$hostname ](bold $style)'
disabled = false

[os]
disabled = false
style = "bg:#ffb3b2 fg:#561d1f"
format = '[$symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
Kali = " "

[directory]
style = "fg:#ffdad9 bg:#733334"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#5d3f3f"
format = '[[ $symbol $branch ](fg:#ffdad9 bg:#5d3f3f)]($style)'

[git_status]
style = "bg:#5d3f3f"
format = '[[($all_status$ahead_behind )](fg:#ffdad9 bg:#5d3f3f)]($style)'

[nodejs]
symbol = ""
style = "bg:#322827"
format = '[[ $symbol ($version) ](fg:#ffb3b2 bg:#322827)]($style)'

[rust]
symbol = ""
style = "bg:#322827"
format = '[[ $symbol ($version) ](fg:#e6bdbb bg:#322827)]($style)'

[golang]
symbol = ""
style = "bg:#322827"
format = '[[ $symbol ($version) ](fg:#e4c18d bg:#322827)]($style)'

[php]
symbol = ""
style = "bg:#322827"
format = '[[ $symbol ($version) ](fg:#ffdad9 bg:#322827)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#271d1d"
format = '[[ $time ](fg:#d7c1c0 bg:#271d1d)]($style)'