[window]
opacity = 0.85
blur = true
padding = { x = 4, y = 4 }
decorations = "Transparent"
dynamic_padding = true
title = "Terminal"

[scrolling]
history = 50000

[font]
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
